[versions]
agp = "8.10.1"
#   This is for androidx.annotation.NonNull class for Java
#   annotationJvm = "1.9.1"
#   Uncomment this if using Kotlin
kotlin = "2.0.21"

[libraries]
#   androidx-annotation-jvm = { group = "androidx.annotation", name = "annotation-jvm", version.ref = "annotationJvm" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
#   Uncomment this if using Kotlin
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
